// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TherapEase.Infrastructure.Persistencia;

#nullable disable

namespace TherapEase.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoDeDatos))]
    partial class ContextoDeDatosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TherapEase.Domain.Auditoria.EventoAuditoria", b =>
                {
                    b.Property<Guid>("IdEvento")
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.PrimitiveCollection<string[]>("CamposAfectados")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("FechaEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hecho")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("IdRegistro")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuarioActor")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdEvento");

                    b.HasIndex("FechaEvento");

                    b.HasIndex("TipoRegistro", "IdRegistro", "FechaEvento");

                    b.ToTable("EventoAuditoria", (string)null);
                });

            modelBuilder.Entity("TherapEase.Domain.Citas.Cita", b =>
                {
                    b.Property<Guid>("IdCita")
                        .HasColumnType("uuid");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdPaciente")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdUsuarioActualizacion")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuarioAlta")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdUsuarioBaja")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("IdCita");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Cita", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cita_Ambito", "\"Ambito\" IN ('Escolar', 'Independiente')");

                            t.HasCheckConstraint("CK_Cita_BajaCoherente", "(\"Condicion\" = 'Vigente' AND \"FechaBaja\" IS NULL AND \"IdUsuarioBaja\" IS NULL) OR (\"Condicion\" = 'Baja' AND \"FechaBaja\" IS NOT NULL AND \"IdUsuarioBaja\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Cita_Estado", "\"Estado\" IN ('Agendada', 'Cancelada')");

                            t.HasCheckConstraint("CK_Cita_EstadoPago", "\"EstadoPago\" IN ('Pendiente', 'Pagado')");

                            t.HasCheckConstraint("CK_Cita_InicioAntesDeFin", "\"Inicio\" < \"Fin\"");
                        });
                });

            modelBuilder.Entity("TherapEase.Domain.Pacientes.Paciente", b =>
                {
                    b.Property<Guid>("IdPaciente")
                        .HasColumnType("uuid");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Contacto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdUsuarioActualizacion")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuarioAlta")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdUsuarioBaja")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("IdPaciente");

                    b.ToTable("Paciente", null, t =>
                        {
                            t.HasCheckConstraint("CK_Paciente_BajaCoherente", "(\"Condicion\" = 'Vigente' AND \"FechaBaja\" IS NULL AND \"IdUsuarioBaja\" IS NULL) OR (\"Condicion\" = 'Baja' AND \"FechaBaja\" IS NOT NULL AND \"IdUsuarioBaja\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Paciente_NombreNoVacio", "length(btrim(\"Nombre\")) > 0");
                        });
                });

            modelBuilder.Entity("TherapEase.Domain.Pacientes.PacienteAmbito", b =>
                {
                    b.Property<Guid>("IdPaciente")
                        .HasColumnType("uuid");

                    b.Property<string>("Ambito")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdPaciente", "Ambito");

                    b.ToTable("PacienteAmbito", null, t =>
                        {
                            t.HasCheckConstraint("CK_PacienteAmbito_Ambito", "\"Ambito\" IN ('Escolar', 'Independiente')");
                        });
                });

            modelBuilder.Entity("TherapEase.Domain.Citas.Cita", b =>
                {
                    b.HasOne("TherapEase.Domain.Pacientes.Paciente", null)
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TherapEase.Domain.Pacientes.PacienteAmbito", b =>
                {
                    b.HasOne("TherapEase.Domain.Pacientes.Paciente", null)
                        .WithMany("Ambitos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TherapEase.Domain.Pacientes.Paciente", b =>
                {
                    b.Navigation("Ambitos");
                });
#pragma warning restore 612, 618
        }
    }
}
